FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN pip3 install --no-cache-dir -r requirements.txt

ARG fargate_cluster
ARG task_definition
ARG subnet_id
ARG max_workers
ARG max_idle_time

ENV fargate_cluster=${fargate_cluster}
ENV task_definition=${task_definition}
ENV subnet_id=${subnet_id}
ENV max_workers=${max_workers}
ENV max_idle_time=${max_idle_time}

# Specify the command to run on container start
CMD ["python3", "app/orchestration.py"]